### ISSUE TITLE
Read and execute xarray doumentation and examples.

### ISSUE THREAD

**Issue by hdsingh** [intake/intake-gsoc-gui#2]
This issue is more of a pre-coding task to be done by me. It will increase my understanding of Xarray.

**Task**:  Read  documentation and execute tutorials available at [Xarray: N-D labeled arrays and datasets in Python](http://xarray.pydata.org/en/stable/).

**Comment by rsignell-usgs** [comment]
@hdsingh , as part of the community phase of your GSoC, perhaps also get a feeling for what the xarray community is thinking about on this [blog post by Ryan Abernathy](https://medium.com/pangeo/supporting-new-xarray-contributors-6c42b12b0811) and this follow-up [post by Benoît Bovy](https://medium.com/pangeo/thoughts-on-the-state-of-xarray-within-the-broader-scientific-python-ecosystem-5cee3c59cd2b)

**Comment by hdsingh** [comment]
Yes, sir I will go through these posts.

**Comment by hdsingh** [comment]
I have read these posts. These have given me a better status of `xarray`. It has a lot of useful features (so much more than simple pandas) but is not well known beyond Earth Sciences. It is also facing a problem of wide adoption because of being less popular. It has a lot of potential and needs more contributions from developers to exploit it further. I will try to solve some issues and contribute to  `xarray` after this project.

**Comment by hdsingh** [comment]
I opened this issue https://github.com/pydata/xarray/issues/2980.

Also sent a request to @rabernat, to add me in [Xarray Google Group](https://groups.google.com/forum/#!forum/xarray)  for discussion with xarray community, and also to know his ideas and thoughts about our project.


Current status
- [x] [Data Structures](http://xarray.pydata.org/en/stable/data-structures.html)
- [x] [Indexing and selecting data](http://xarray.pydata.org/en/stable/indexing.html)
- [x] [Interpolating data](http://xarray.pydata.org/en/stable/interpolation.html)
- [x] [Computation](http://xarray.pydata.org/en/stable/computation.html)
- [x] [GroupBy: split-apply-combine](http://xarray.pydata.org/en/stable/groupby.html)
- [x] [Reshaping and reorganizing data ](http://xarray.pydata.org/en/stable/reshaping.html)
- [x] [Combining data](http://xarray.pydata.org/en/stable/combining.html)
- [x] [Time series data](http://xarray.pydata.org/en/stable/time-series.html)
- [x] [Weather and climate data](http://xarray.pydata.org/en/stable/weather-climate.html)
- [x] [Working with pandas](http://xarray.pydata.org/en/stable/pandas.html)
- [x] [Plotting](http://xarray.pydata.org/en/stable/plotting.html)
- [x] [Examples](http://xarray.pydata.org/en/stable/examples.html)

**Comment by hdsingh** [comment]
Completed.
