### ISSUE TITLE
Go through the pyviz and other tutorials once again

### ISSUE THREAD

**Issue by hdsingh** [intake/intake-gsoc-gui#3]
This issue is also pre-coding task. 

**Tasks**:
Read and execute the following tutorials:
1. [PyViz Tutorial — PyViz documentation](http://pyviz.org/tutorial/index.html)
2. [User Guide — HoloViews](http://holoviews.org/user_guide/index.html)
3.  [Reference Guide — HoloViews](http://holoviews.org/reference/index.html)
4. [User Guide — GeoViews documentation](http://geoviews.org/user_guide/index.html)
5. [Gallery — GeoViews documentation](http://geoviews.org/gallery/index.html)
6. [User Guide — Panel documentation](https://pyviz-dev.github.io/panel/user_guide/index.html)
7. [Reference Guide -- Panel 0.5.1. documentation](https://pyviz-dev.github.io/panel/reference/index.html)
8. [User Guide — hvPlot](https://hvplot.pyviz.org/user_guide/index.html)

**Comment by hdsingh** [comment]
Current status
- [x] [PyViz Tutorial — PyViz documentation](http://pyviz.org/tutorial/index.html)
- [x] [User Guide — HoloViews](http://holoviews.org/user_guide/index.html)
- [x] [Reference Guide — HoloViews](http://holoviews.org/reference/index.html)
- [x] [User Guide — GeoViews documentation](http://geoviews.org/user_guide/index.html)
- [x] [Gallery — GeoViews documentation](http://geoviews.org/gallery/index.html)
- [x] [User Guide — Panel documentation](https://pyviz-dev.github.io/panel/user_guide/index.html)
- [x] [Gallery — Panel](https://pyviz-dev.github.io/panel/gallery/index.html) `Some examples need more time so will reference these as needed`
- [x] [User Guide — hvPlot](https://hvplot.pyviz.org/user_guide/index.html)

**Comment by hdsingh** [comment]
Completed.
